"""
Hermes Life OS - Notifications
=================================
Pluggable delivery channels for briefings generated by the scheduler
(or manually): console (always available), a generic webhook (POST
JSON), Telegram (Bot API), and email (SMTP). Stdlib only - no extra
dependencies required.

Channel selection and credentials come from environment variables so
no secrets ever need to live in code or config files:

    HERMES_NOTIFY_CHANNEL   console | webhook | telegram | email  (default: console)

    Webhook:
        HERMES_WEBHOOK_URL

    Telegram:
        TELEGRAM_BOT_TOKEN
        TELEGRAM_CHAT_ID

    Email (SMTP):
        HERMES_SMTP_HOST
        HERMES_SMTP_PORT      (default: 587)
        HERMES_SMTP_USER
        HERMES_SMTP_PASSWORD
        HERMES_SMTP_TO        (recipient address; defaults to HERMES_SMTP_USER)

Every send_notification() call also prints to console regardless of
channel, so nothing is ever silently lost if a remote channel fails.
"""

from __future__ import annotations

import json
import os
import smtplib
import urllib.request
import urllib.error
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dataclasses import dataclass
from typing import Optional


class NotificationError(Exception):
    """Raised when a non-console delivery channel fails."""


@dataclass
class NotificationResult:
    channel: str
    ok: bool
    detail: str = ""


def _env(key: str, default: Optional[str] = None) -> Optional[str]:
    val = os.environ.get(key, default)
    return val if val else default


# ---------------------------------------------------------------------------
# Individual channel senders - each raises NotificationError on failure
# ---------------------------------------------------------------------------

def _send_console(title: str, message: str) -> NotificationResult:
    print(f"\n=== {title} ===\n{message}\n")
    return NotificationResult(channel="console", ok=True)


def _send_webhook(title: str, message: str, url: Optional[str] = None) -> NotificationResult:
    url = url or _env("HERMES_WEBHOOK_URL")
    if not url:
        raise NotificationError("HERMES_WEBHOOK_URL is not set")
    payload = json.dumps({"title": title, "message": message}).encode("utf-8")
    req = urllib.request.Request(
        url, data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            status = resp.status
    except urllib.error.URLError as e:
        raise NotificationError(f"webhook request failed: {e}") from e
    if status >= 300:
        raise NotificationError(f"webhook returned status {status}")
    return NotificationResult(channel="webhook", ok=True, detail=f"status={status}")


def _send_telegram(title: str, message: str,
                    bot_token: Optional[str] = None,
                    chat_id: Optional[str] = None) -> NotificationResult:
    bot_token = bot_token or _env("TELEGRAM_BOT_TOKEN")
    chat_id = chat_id or _env("TELEGRAM_CHAT_ID")
    if not bot_token or not chat_id:
        raise NotificationError("TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID must both be set")

    text = f"*{title}*\n\n{message}"
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    payload = json.dumps({
        "chat_id": chat_id,
        "text": text,
        "parse_mode": "Markdown",
    }).encode("utf-8")
    req = urllib.request.Request(
        url, data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            body = json.loads(resp.read().decode("utf-8"))
    except urllib.error.URLError as e:
        raise NotificationError(f"telegram request failed: {e}") from e
    if not body.get("ok"):
        raise NotificationError(f"telegram API error: {body}")
    return NotificationResult(channel="telegram", ok=True)


def _send_email(title: str, message: str,
                 host: Optional[str] = None, port: Optional[int] = None,
                 user: Optional[str] = None, password: Optional[str] = None,
                 to: Optional[str] = None) -> NotificationResult:
    host = host or _env("HERMES_SMTP_HOST")
    port = port or int(_env("HERMES_SMTP_PORT", "587"))
    user = user or _env("HERMES_SMTP_USER")
    password = password or _env("HERMES_SMTP_PASSWORD")
    to = to or _env("HERMES_SMTP_TO", user)

    if not host or not user or not password or not to:
        raise NotificationError(
            "HERMES_SMTP_HOST, HERMES_SMTP_USER, HERMES_SMTP_PASSWORD and a "
            "recipient (HERMES_SMTP_TO or HERMES_SMTP_USER) must all be set"
        )

    msg = MIMEText(message, "plain", "utf-8")
    msg["Subject"] = title
    msg["From"] = user
    msg["To"] = to

    try:
        with smtplib.SMTP(host, port, timeout=10) as server:
            server.starttls()
            server.login(user, password)
            server.sendmail(user, [to], msg.as_string())
    except (smtplib.SMTPException, OSError) as e:
        raise NotificationError(f"email send failed: {e}") from e
    return NotificationResult(channel="email", ok=True)


_SENDERS = {
    "webhook": _send_webhook,
    "telegram": _send_telegram,
    "email": _send_email,
}


def send_html_email(subject: str, html_body: str, plain_body: Optional[str] = None,
                     host: Optional[str] = None, port: Optional[int] = None,
                     user: Optional[str] = None, password: Optional[str] = None,
                     to: Optional[str] = None) -> NotificationResult:
    """Sends a richer HTML email (used by weekly_email.py for the
    dashboard report) alongside a plain-text fallback for clients that
    don't render HTML. Same HERMES_SMTP_* env vars as _send_email/the
    'email' notification channel - this is a separate function rather
    than extending _send_email because the notification channels are
    plain-text by design (a short briefing/alert), while this is
    specifically for sending a full HTML report."""
    host = host or _env("HERMES_SMTP_HOST")
    port = port or int(_env("HERMES_SMTP_PORT", "587"))
    user = user or _env("HERMES_SMTP_USER")
    password = password or _env("HERMES_SMTP_PASSWORD")
    to = to or _env("HERMES_SMTP_TO", user)

    if not host or not user or not password or not to:
        raise NotificationError(
            "HERMES_SMTP_HOST, HERMES_SMTP_USER, HERMES_SMTP_PASSWORD and a "
            "recipient (HERMES_SMTP_TO or HERMES_SMTP_USER) must all be set"
        )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = user
    msg["To"] = to
    if plain_body:
        msg.attach(MIMEText(plain_body, "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    try:
        with smtplib.SMTP(host, port, timeout=10) as server:
            server.starttls()
            server.login(user, password)
            server.sendmail(user, [to], msg.as_string())
    except (smtplib.SMTPException, OSError) as e:
        raise NotificationError(f"email send failed: {e}") from e
    return NotificationResult(channel="email", ok=True)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def send_notification(title: str, message: str, channel: Optional[str] = None) -> NotificationResult:
    """
    Deliver a notification. Always prints to console. If `channel` (or the
    HERMES_NOTIFY_CHANNEL env var) names a remote channel, also attempts
    delivery there; failures are caught and reported (never raised) so a
    broken webhook/Telegram/email config never crashes the scheduler.
    """
    console_result = _send_console(title, message)

    channel = channel or _env("HERMES_NOTIFY_CHANNEL", "console")
    if channel in (None, "console"):
        return console_result

    sender = _SENDERS.get(channel)
    if sender is None:
        return NotificationResult(
            channel=channel, ok=False,
            detail=f"unknown channel '{channel}', delivered to console only",
        )

    try:
        return sender(title, message)
    except NotificationError as e:
        print(f"[notifications] {channel} delivery failed: {e}")
        return NotificationResult(channel=channel, ok=False, detail=str(e))
